import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';

// Deterministic adapter: keep numeric contract; next/font/local loads fonts once.
const source = new URL('../docs/design/v1.0/05-implementation/layout-contract.css', import.meta.url);
const target = new URL('../src/styles/layout.generated.css', import.meta.url);
const original = (await readFile(source, 'utf8')).replace(/\r\n/g, '\n');
assert.equal((original.match(/@import url\("\.\/fonts\.css"\);/g) ?? []).length, 1);
const expected = '/* Generated by scripts/prepare-layout.mjs; do not edit. */\n' + original.replace('@import url("./fonts.css");', '');
if (process.argv.includes('--check')) assert.equal(await readFile(target, 'utf8'), expected, 'Regenerate layout with node scripts/prepare-layout.mjs');
else await writeFile(target, expected);
